# -------------------------
# 1️⃣ Build Stage (Vite)
# -------------------------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# REQUIRED so Vite loads .env.production
ENV NODE_ENV=production

# Optional but helps debugging build
ARG VITE_API_URL
ENV REACT_APP_API_URL=$VITE_API_URL

RUN npm run build


# -------------------------
# 2️⃣ Serve with NGINX
# -------------------------
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

