version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - portfolio-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    volumes:
      - ./media:/usr/share/nginx/html/media
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge


