apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi

