apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
      - name: portfolio-backend
        image: portfoliovijay.azurecr.io/portfolio-backend:build-164
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: backend.settings

        volumeMounts:
        - name: backend-storage
          mountPath: /app/media
                  
        - name: backend-storage
          mountPath: /app/db    
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-storage

      imagePullSecrets:
      - name: acr-secret

