apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend
  namespace: portfolio
spec:
  selector:
    app: portfolio-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

