apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: portfolio-backend
                port:
                  number: 8000

          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: portfolio-backend
                port:
                  number: 8000

          - path: /static
            pathType: Prefix
            backend:
              service:
                name: portfolio-backend
                port:
                  number: 8000

          - path: /media
            pathType: Prefix
            backend:
              service:
                name: portfolio-backend
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-frontend
                port:
                  number: 80

