# Generated by Django 5.2.8 on 2025-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(choices=[('Present', 'Present'), ('Jan 2024', 'Jan 2024'), ('Dec 2023', 'Dec 2023'), ('Jun 2023', 'Jun 2023'), ('2022', '2022'), ('Custom', 'Custom')], default='Present', max_length=50),
        ),
    ]
