# Generated by Django 5.2.8 on 2025-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
