# Generated by Django 5.2.8 on 2025-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_image',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
