# Generated by Django 5.2.8 on 2025-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_whyhireme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('projects', models.TextField()),
                ('certifications', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
