# Generated by Django 5.2.8 on 2025-12-03 11:36

import django.db.models.deletion
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_profile_created_at_profile_public_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-is_current', 'order')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='aiprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_profiles', to='portfolio.profile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolio.profile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile'),
        ),
        migrations.AddField(
            model_name='whyhireme',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whyhiremes', to='portfolio.profile'),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
