# Generated by Django 5.2.8 on 2025-12-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_certification_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='portfolio.profile'),
        ),
    ]
