# Generated by Django 5.2.8 on 2025-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_contactmessage_options_contactmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
